global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rule.yml"
  # - "second_rule.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # ZFS Exporter (disabled - using textfile collector instead)
  # - job_name: 'zfs-exporter'
  #   static_configs:
  #     - targets: ['zfs-exporter:9134']

  # Process Exporter - System process metrics
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']

  # Add more exporters here as needed
  # - job_name: 'nginx-exporter'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
